name: CI

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install graphviz

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build SVG
      run: dot article_references.dot -T svg -O

    - name: Build PNG
      run: dot article_references.dot -T png -O

    - name: Build GIF
      run: dot article_references.dot -T gif -O

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          path: article_references.dot.*
